server:
  port: 9000

spring:
  application:
    name: tradeclient
  zipkin:
      baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

